[commands.swipe.three]
up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Parachute"
down = "yakuake"
left = "xdotool key alt+Tab"
right = "xdotool key alt+shift+Tab"

[commands.swipe.four]
up = ""
down = ""
left = "qdbus org.kde.KWin /KWin org.kde.KWin.setCurrentDesktop $(((`qdbus org.kde.KWin /KWin org.kde.KWin.currentDesktop`) % 2 + 1))"
right = "qdbus org.kde.KWin /KWin org.kde.KWin.setCurrentDesktop $(((`qdbus org.kde.KWin /KWin org.kde.KWin.currentDesktop`) % 2 + 1))"

