[commands.swipe.three]
up = "xdotool key ctrl+alt+d"
down = "yakuake"
left = "xdotool key alt+Tab"
right = "xdotool key alt+shift+Tab"

[commands.swipe.four]
up = ""
down = ""
left = "qdbus org.kde.KWin /KWin org.kde.KWin.setCurrentDesktop $(((`qdbus org.kde.KWin /KWin org.kde.KWin.currentDesktop`) % 3 + 1))"
right = "qdbus org.kde.KWin /KWin org.kde.KWin.setCurrentDesktop $(((`qdbus org.kde.KWin /KWin org.kde.KWin.currentDesktop` + 1) % 3 + 1))"

